server.port: ${port:8080}

security.basic.enabled: false

#shell.auth: spring
#shell.auth.spring.roles:
#shell.ssh.port:

management:
  context-path: /management
#    security.role: ADMIN

#spring.view.prefix: /WEB-INF/pages/
#spring.view.suffix: .html

---

spring:
  profiles: dev

debug: true

spring.data.mongodb:
  host: localhost
  database: boot-groovy
  port: 27017

---

spring:
  profiles: heroku

spring.data.mongodb:
  uri: ${MONGOHQ_URL}