server.port: ${port:8080}

#debug: true

security.basic.enabled: false

#shell.auth: spring
#shell.auth.spring.roles:
#shell.ssh.port:

management:
  context-path: /management
#    security.role: ADMIN
